update memo

diff --git a/memo b/memo
--- a/memo
+++ b/memo
@@ -2,11 +2,21 @@
 
 # set -o errexit
 
+
+###
+#
+# Usage example:
+# memo --ttl=60s -- wget http://speedtest.tele2.net/1MB.zip
+#
+###
+
 #
 # Helpers
 #
 
 TTL=60s
+DIR=$(pwd)
+CACHE_DIR=${BKT_TMPDIR:-"$HOME/.cache/bkt"}
 
 # https://konsolebox.io/blog/2022/05/14/general-command-line-parsing-solution-without-using-getopt-s.html
 function get_opt_arg {
@@ -49,38 +59,32 @@ benchmark() {
 # Main
 #
 
-
-DIR=$(pwd)
-
 TEMPDIR=$(mktemp -d)
 B64KEY=$(echo "$CMD" | base64)
+SHAKEY=$(echo "$B64KEY" | shasum | cut -d ' ' -f1)
+SCOPE="memo.$SHAKEY"
 
+# Check if command is already cached
 cd $TEMPDIR
+TIME=$(bkt --cache-dir $CACHE_DIR --scope="$SCOPE" --ttl $TTL -- bash -c "date +%s.%N; echo \"$B64KEY\" > \"$B64KEY.ttl\"") #&> /dev/null
 
-
-echo $B64KEY
-
-TIME=$(bkt --ttl $TTL -- bash -c "date +%s.%N; echo \"$B64KEY\" > \"$B64KEY.ttl\"") #&> /dev/null
-
+# If not cached - run command again
 if [[ -f "$B64KEY.ttl" ]]; then
   cd $DIR
   eval "$CMD"
   code=$?
-  echo "code: $code"
 
+  # If exit code > 0 - delete the cache key (emulate behavior of `bkt --discard-failures`)
   if [ $code -ne 0 ]; then
-    echo "code not zero"
-    cd $TEMPDIR
-    #bkt --force --ttl 1s -- bash -c "date +%s.%N; echo \"$B64KEY\" > \"$B64KEY.ttl\""
+    cd $CACHE_DIR || (echo 'Cache dir does not exist'; exit 1)
+    rm -f $(realpath ./bkt*-cache/keys/$SCOPE*)
+    rm -f ./bkt*-cache/keys/$SCOPE*
+
     exit $code
   fi
 
-  # TIME=$(bkt --ttl $TTL -- bash -c "date +%s.%N; echo \"$B64KEY\" > \"$B64KEY.ttl\"") #&> /dev/null
-
 else
-  echo "[cached] $CMD"
+  # Else, command is cached
   TTL_SINCE=$(printf %.1f $(benchmark $TIME) | bc -l)
-  echo "[$TTL_SINCE of $TTL]"
+  echo "[cached - $TTL_SINCE of $TTL] $CMD"
 fi
-
-
